name: revan_client
description: Dart client for Revan API.
version: 0.1.0
repository: https://github.com/greymag/revan_client
issue_tracker: https://github.com/greymag/revan_client/issues

environment:
  sdk: ^3.5.0

dependencies:
  async: ^2.13.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.24.0
